CREATE TABLE Teams
(
ID INT NOT NULL,
TeamName VARCHAR(100) NOT NULL,
Tag VARCHAR(100) NULL,
TimeCreated VARCHAR(100) NULL,
Rating VARCHAR(100) NULL,
Logo VARCHAR(100) NULL,
LogoSponsor VARCHAR(100) NULL,
CountryCode VARCHAR(100) NULL,
URL VARCHAR(100) NULL,
GamesPlayed INT NULL,
AdminAccount INT NULL,
PRIMARY KEY (ID)
)

--DROP TABLE dbo.Teams