SELECT  SteamID ,
        SteamID64 ,
        PersonaName ,
        ProfileURL ,
        Avatar ,
        AvatarMedium ,
        AvatarFull ,
        PersonaState ,
        CommunityVisibilityState ,
        ProfileState ,
        LastLogOff ,
        CommentPermission ,
        RealName ,
        PrimaryClanID ,
        TimeCreated ,
        GameID ,
        GameServerID ,
        GameExtraInfo ,
        CityID ,
        LocCountyCode ,
        LocStateCode ,
        LocCityID ,
        LastUpdated ,
        OldestMatchFound INTO #Players FROM dbo.Players

		DROP TABLE dbo.Players

		CREATE TABLE [dbo].[Players]
(
[SteamID] [int] NOT NULL,
[SteamID64] [bigint] NULL CONSTRAINT [DF_Players_SteamID] DEFAULT ((0)),
[PersonaName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProfileURL] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Avatar] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AvatarMedium] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AvatarFull] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonaState] [int] NULL,
[CommunityVisibilityState] [int] NULL,
[ProfileState] [int] NULL,
[LastLogOff] [datetime] NULL,
[CommentPermission] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RealName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryClanID] [bigint] NULL,
[TimeCreated] [datetime] NULL,
[GameID] [int] NULL,
[GameServerID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GameExtraInfo] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityID] [int] NULL,
[LocCountyCode] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocStateCode] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocCityID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastUpdated] [datetime] NOT NULL CONSTRAINT [DF_Players_LastUpdated] DEFAULT (getdate()),
[OldestMatchFound] [bit] NOT NULL CONSTRAINT [DF_Players_OldestMatchFound] DEFAULT ((0)),
IsPrivate BIT CONSTRAINT DF_Players_IsPrivate DEFAULT 0
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Players] ADD CONSTRAINT [PK_Players_SteamID] PRIMARY KEY CLUSTERED  ([SteamID]) ON [PRIMARY]
GO


INSERT INTO dbo.Players
        ( SteamID ,
          SteamID64 ,
          PersonaName ,
          ProfileURL ,
          Avatar ,
          AvatarMedium ,
          AvatarFull ,
          PersonaState ,
          CommunityVisibilityState ,
          ProfileState ,
          LastLogOff ,
          CommentPermission ,
          RealName ,
          PrimaryClanID ,
          TimeCreated ,
          GameID ,
          GameServerID ,
          GameExtraInfo ,
          CityID ,
          LocCountyCode ,
          LocStateCode ,
          LocCityID ,
          LastUpdated ,
          OldestMatchFound
        )
		SELECT  SteamID ,
		        SteamID64 ,
		        PersonaName ,
		        ProfileURL ,
		        Avatar ,
		        AvatarMedium ,
		        AvatarFull ,
		        PersonaState ,
		        CommunityVisibilityState ,
		        ProfileState ,
		        LastLogOff ,
		        CommentPermission ,
		        RealName ,
		        PrimaryClanID ,
		        TimeCreated ,
		        GameID ,
		        GameServerID ,
		        GameExtraInfo ,
		        CityID ,
		        LocCountyCode ,
		        LocStateCode ,
		        LocCityID ,
		        LastUpdated ,
		        OldestMatchFound FROM #Players