SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `DotaDB` ;
CREATE SCHEMA IF NOT EXISTS `DotaDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DotaDB` ;

-- -----------------------------------------------------
-- Table `DotaDB`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DotaDB`.`Players` ;

CREATE TABLE IF NOT EXISTS `DotaDB`.`Players` (
  `SteamID` INT NOT NULL,
  `PersonaName` VARCHAR(45) NULL,
  `ProfileURL` VARCHAR(45) NULL,
  `Avatar` VARCHAR(45) NULL,
  `AvatarMedium` VARCHAR(45) NULL,
  `AvatarFull` VARCHAR(45) NULL,
  `PersonaState` VARCHAR(45) NULL,
  `CommunityVisibilityState` VARCHAR(45) NULL,
  PRIMARY KEY (`SteamID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
