

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class ProblemsRelated : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ProblemsRelated entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProblemsRelated()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProblemsRelated(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProblemsRelated> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ProblemsRelated.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProblemsRelated_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProblemsRelated_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.ProblemsRelated.DetailsClass.GetValue(this, global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> IsActive
        {
            get
            {
                return global::LightSwitchApplication.ProblemsRelated.DetailsClass.GetValue(this, global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.IsActive);
            }
            set
            {
                global::LightSwitchApplication.ProblemsRelated.DetailsClass.SetValue(this, global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.IsActive, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsActive_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsActive_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsActive_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.problem problem
        {
            get
            {
                return global::LightSwitchApplication.ProblemsRelated.DetailsClass.GetValue(this, global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem);
            }
            set
            {
                global::LightSwitchApplication.ProblemsRelated.DetailsClass.SetValue(this, global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void problem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void problem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void problem_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.problem problem1
        {
            get
            {
                return global::LightSwitchApplication.ProblemsRelated.DetailsClass.GetValue(this, global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem1);
            }
            set
            {
                global::LightSwitchApplication.ProblemsRelated.DetailsClass.SetValue(this, global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void problem1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void problem1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void problem1_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ProblemsRelated,
                global::LightSwitchApplication.ProblemsRelated.DetailsClass,
                global::LightSwitchApplication.ProblemsRelated.DetailsClass.IImplementation,
                global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass>.Entry
                __ProblemsRelatedEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass>.Entry(
                    global::LightSwitchApplication.ProblemsRelated.DetailsClass.__ProblemsRelated_CreateNew,
                    global::LightSwitchApplication.ProblemsRelated.DetailsClass.__ProblemsRelated_Created,
                    global::LightSwitchApplication.ProblemsRelated.DetailsClass.__ProblemsRelated_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ProblemsRelated __ProblemsRelated_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProblemsRelated> es)
            {
                return new global::LightSwitchApplication.ProblemsRelated(es);
            }
            private static void __ProblemsRelated_Created(global::LightSwitchApplication.ProblemsRelated e)
            {
                e.ProblemsRelated_Created();
            }
            private static bool __ProblemsRelated_AllowSaveWithErrors(global::LightSwitchApplication.ProblemsRelated e)
            {
                bool result = false;
                e.ProblemsRelated_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::System.Nullable<int>> IsActive
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.IsActive) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem> problem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem> problem1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID { get; }
                new global::System.Nullable<int> IsActive { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation problem { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation problem1 { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProblemsRelated.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.ProblemsRelated e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.ProblemsRelated e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.ProblemsRelated e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::System.Nullable<int>>.Entry
                    IsActive = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::System.Nullable<int>>.Entry(
                        "IsActive",
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._IsActive_Stub,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._IsActive_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._IsActive_Validate,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._IsActive_GetImplementationValue,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._IsActive_SetImplementationValue,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._IsActive_OnValueChanged);
                private static void _IsActive_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.ProblemsRelated.DetailsClass d, object sf)
                {
                    c(d, ref d._IsActive, sf);
                }
                private static bool _IsActive_ComputeIsReadOnly(global::LightSwitchApplication.ProblemsRelated e)
                {
                    bool result = false;
                    e.IsActive_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsActive_Validate(global::LightSwitchApplication.ProblemsRelated e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsActive_Validate(r);
                }
                private static global::System.Nullable<int> _IsActive_GetImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass d)
                {
                    return d.ImplementationEntity.IsActive;
                }
                private static void _IsActive_SetImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.IsActive = v;
                }
                private static void _IsActive_OnValueChanged(global::LightSwitchApplication.ProblemsRelated e)
                {
                    e.IsActive_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem>.Entry
                    problem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem>.Entry(
                        "problem",
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem_Stub,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem_Validate,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem_GetCoreImplementationValue,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem_GetImplementationValue,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem_SetImplementationValue,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem_Refresh,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem_OnValueChanged);
                private static void _problem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem>.Data> c, global::LightSwitchApplication.ProblemsRelated.DetailsClass d, object sf)
                {
                    c(d, ref d._problem, sf);
                }
                private static bool _problem_ComputeIsReadOnly(global::LightSwitchApplication.ProblemsRelated e)
                {
                    bool result = false;
                    e.problem_IsReadOnly(ref result);
                    return result;
                }
                private static void _problem_Validate(global::LightSwitchApplication.ProblemsRelated e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.problem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _problem_GetCoreImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass d)
                {
                    return d.ImplementationEntity.problem;
                }
                private static global::LightSwitchApplication.problem _problem_GetImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.problem, global::LightSwitchApplication.problem.DetailsClass>(global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem, ref d._problem);
                }
                private static void _problem_SetImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass d, global::LightSwitchApplication.problem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem, ref d._problem, (i, ev) => i.problem = ev, v);
                }
                private static void _problem_Refresh(global::LightSwitchApplication.ProblemsRelated.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem, ref d._problem);
                }
                private static void _problem_OnValueChanged(global::LightSwitchApplication.ProblemsRelated e)
                {
                    e.problem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem>.Entry
                    problem1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem>.Entry(
                        "problem1",
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem1_Stub,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem1_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem1_Validate,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem1_GetCoreImplementationValue,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem1_GetImplementationValue,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem1_SetImplementationValue,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem1_Refresh,
                        global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties._problem1_OnValueChanged);
                private static void _problem1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem>.Data> c, global::LightSwitchApplication.ProblemsRelated.DetailsClass d, object sf)
                {
                    c(d, ref d._problem1, sf);
                }
                private static bool _problem1_ComputeIsReadOnly(global::LightSwitchApplication.ProblemsRelated e)
                {
                    bool result = false;
                    e.problem1_IsReadOnly(ref result);
                    return result;
                }
                private static void _problem1_Validate(global::LightSwitchApplication.ProblemsRelated e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.problem1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _problem1_GetCoreImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass d)
                {
                    return d.ImplementationEntity.problem1;
                }
                private static global::LightSwitchApplication.problem _problem1_GetImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.problem, global::LightSwitchApplication.problem.DetailsClass>(global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem1, ref d._problem1);
                }
                private static void _problem1_SetImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass d, global::LightSwitchApplication.problem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem1, ref d._problem1, (i, ev) => i.problem1 = ev, v);
                }
                private static void _problem1_Refresh(global::LightSwitchApplication.ProblemsRelated.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ProblemsRelated.DetailsClass.PropertySetProperties.problem1, ref d._problem1);
                }
                private static void _problem1_OnValueChanged(global::LightSwitchApplication.ProblemsRelated e)
                {
                    e.problem1_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::System.Nullable<int>>.Data _IsActive;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem>.Data _problem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProblemsRelated, global::LightSwitchApplication.ProblemsRelated.DetailsClass, global::LightSwitchApplication.problem>.Data _problem1;
            
        }
    
        #endregion
    }
    
    #endregion
}
