

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class tblNote : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the tblNote entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public tblNote()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public tblNote(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.tblNote> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.tblNote.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblNote_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblNote_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int NoteID
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.NoteID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NoteID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NoteID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NoteID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string note
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.note);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.note, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void note_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void note_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void note_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> addDate
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.addDate);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.addDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void addDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void addDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void addDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string uid
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.uid);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.uid, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void uid_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void uid_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void uid_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> IsPrivate
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.IsPrivate);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.IsPrivate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsPrivate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsPrivate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsPrivate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> IsFuture
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.IsFuture);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.IsFuture, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsFuture_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsFuture_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsFuture_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> FutureDate
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.FutureDate);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.FutureDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FutureDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FutureDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FutureDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> NoteType
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.NoteType);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.NoteType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NoteType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NoteType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NoteType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Time
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.Time);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.Time, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Time_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Time_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Time_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateModified
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.DateModified);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.DateModified, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateModified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateModified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateModified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> RelatedTo
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.RelatedTo);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.RelatedTo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelatedTo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelatedTo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelatedTo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> RelatedFrom
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.RelatedFrom);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.RelatedFrom, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelatedFrom_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelatedFrom_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RelatedFrom_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.problem problem
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.problem);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.problem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void problem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void problem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void problem_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.State State
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.State);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.State, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void State_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void State_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void State_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.tblUser tblUser
        {
            get
            {
                return global::LightSwitchApplication.tblNote.DetailsClass.GetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.tblUser);
            }
            set
            {
                global::LightSwitchApplication.tblNote.DetailsClass.SetValue(this, global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.tblUser, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblUser_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblUser_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblUser_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.tblNote,
                global::LightSwitchApplication.tblNote.DetailsClass,
                global::LightSwitchApplication.tblNote.DetailsClass.IImplementation,
                global::LightSwitchApplication.tblNote.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.NoteID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass>.Entry
                __tblNoteEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass>.Entry(
                    global::LightSwitchApplication.tblNote.DetailsClass.__tblNote_CreateNew,
                    global::LightSwitchApplication.tblNote.DetailsClass.__tblNote_Created,
                    global::LightSwitchApplication.tblNote.DetailsClass.__tblNote_AllowSaveWithErrors);
            private static global::LightSwitchApplication.tblNote __tblNote_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.tblNote> es)
            {
                return new global::LightSwitchApplication.tblNote(es);
            }
            private static void __tblNote_Created(global::LightSwitchApplication.tblNote e)
            {
                e.tblNote_Created();
            }
            private static bool __tblNote_AllowSaveWithErrors(global::LightSwitchApplication.tblNote e)
            {
                bool result = false;
                e.tblNote_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.tblNote.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, int> NoteID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.NoteID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string> note
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.note) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>> addDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.addDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string> uid
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.uid) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>> IsPrivate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.IsPrivate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>> IsFuture
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.IsFuture) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>> FutureDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.FutureDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>> NoteType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.NoteType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>> Time
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.Time) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>> DateModified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.DateModified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>> RelatedTo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.RelatedTo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>> RelatedFrom
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.RelatedFrom) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.problem> problem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.problem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.problem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.State> State
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.State) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.State>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.tblUser> tblUser
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.tblUser) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.tblUser>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int NoteID { get; }
                new string note { get; set; }
                new global::System.Nullable<global::System.DateTime> addDate { get; set; }
                new string uid { get; set; }
                new global::System.Nullable<int> IsPrivate { get; set; }
                new global::System.Nullable<int> IsFuture { get; set; }
                new global::System.Nullable<global::System.DateTime> FutureDate { get; set; }
                new global::System.Nullable<int> NoteType { get; set; }
                new global::System.Nullable<int> Time { get; set; }
                new global::System.Nullable<global::System.DateTime> DateModified { get; set; }
                new global::System.Nullable<int> RelatedTo { get; set; }
                new global::System.Nullable<int> RelatedFrom { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation problem { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation State { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation tblUser { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, int>.Entry
                    NoteID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, int>.Entry(
                        "NoteID",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteID_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteID_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteID_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteID_OnValueChanged);
                private static void _NoteID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, int>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._NoteID, sf);
                }
                private static bool _NoteID_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.NoteID_IsReadOnly(ref result);
                    return result;
                }
                private static void _NoteID_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.NoteID_Validate(r);
                }
                private static int _NoteID_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.NoteID;
                }
                private static void _NoteID_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.NoteID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string>.Entry
                    note = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string>.Entry(
                        "note",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._note_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._note_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._note_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._note_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._note_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._note_OnValueChanged);
                private static void _note_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._note, sf);
                }
                private static bool _note_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.note_IsReadOnly(ref result);
                    return result;
                }
                private static void _note_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.note_Validate(r);
                }
                private static string _note_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.note;
                }
                private static void _note_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, string v)
                {
                    d.ImplementationEntity.note = v;
                }
                private static void _note_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.note_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    addDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "addDate",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._addDate_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._addDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._addDate_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._addDate_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._addDate_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._addDate_OnValueChanged);
                private static void _addDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._addDate, sf);
                }
                private static bool _addDate_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.addDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _addDate_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.addDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _addDate_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.addDate;
                }
                private static void _addDate_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.addDate = global::LightSwitchApplication.tblNote.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _addDate_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.addDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string>.Entry
                    uid = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string>.Entry(
                        "uid",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._uid_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._uid_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._uid_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._uid_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._uid_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._uid_OnValueChanged);
                private static void _uid_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._uid, sf);
                }
                private static bool _uid_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.uid_IsReadOnly(ref result);
                    return result;
                }
                private static void _uid_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.uid_Validate(r);
                }
                private static string _uid_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.uid;
                }
                private static void _uid_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, string v)
                {
                    d.ImplementationEntity.uid = v;
                }
                private static void _uid_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.uid_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry
                    IsPrivate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry(
                        "IsPrivate",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsPrivate_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsPrivate_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsPrivate_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsPrivate_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsPrivate_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsPrivate_OnValueChanged);
                private static void _IsPrivate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._IsPrivate, sf);
                }
                private static bool _IsPrivate_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.IsPrivate_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsPrivate_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsPrivate_Validate(r);
                }
                private static global::System.Nullable<int> _IsPrivate_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.IsPrivate;
                }
                private static void _IsPrivate_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.IsPrivate = v;
                }
                private static void _IsPrivate_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.IsPrivate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry
                    IsFuture = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry(
                        "IsFuture",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsFuture_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsFuture_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsFuture_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsFuture_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsFuture_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._IsFuture_OnValueChanged);
                private static void _IsFuture_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._IsFuture, sf);
                }
                private static bool _IsFuture_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.IsFuture_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsFuture_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsFuture_Validate(r);
                }
                private static global::System.Nullable<int> _IsFuture_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.IsFuture;
                }
                private static void _IsFuture_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.IsFuture = v;
                }
                private static void _IsFuture_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.IsFuture_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    FutureDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "FutureDate",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._FutureDate_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._FutureDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._FutureDate_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._FutureDate_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._FutureDate_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._FutureDate_OnValueChanged);
                private static void _FutureDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._FutureDate, sf);
                }
                private static bool _FutureDate_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.FutureDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _FutureDate_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FutureDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _FutureDate_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.FutureDate;
                }
                private static void _FutureDate_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.FutureDate = global::LightSwitchApplication.tblNote.DetailsClass.TruncateDate(v);
                }
                private static void _FutureDate_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.FutureDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry
                    NoteType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry(
                        "NoteType",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteType_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteType_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteType_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteType_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteType_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._NoteType_OnValueChanged);
                private static void _NoteType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._NoteType, sf);
                }
                private static bool _NoteType_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.NoteType_IsReadOnly(ref result);
                    return result;
                }
                private static void _NoteType_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.NoteType_Validate(r);
                }
                private static global::System.Nullable<int> _NoteType_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.NoteType;
                }
                private static void _NoteType_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.NoteType = v;
                }
                private static void _NoteType_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.NoteType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry
                    Time = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Time",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._Time_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._Time_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._Time_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._Time_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._Time_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._Time_OnValueChanged);
                private static void _Time_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._Time, sf);
                }
                private static bool _Time_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.Time_IsReadOnly(ref result);
                    return result;
                }
                private static void _Time_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Time_Validate(r);
                }
                private static global::System.Nullable<int> _Time_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.Time;
                }
                private static void _Time_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.Time = v;
                }
                private static void _Time_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.Time_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateModified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateModified",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._DateModified_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._DateModified_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._DateModified_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._DateModified_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._DateModified_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._DateModified_OnValueChanged);
                private static void _DateModified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._DateModified, sf);
                }
                private static bool _DateModified_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.DateModified_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateModified_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateModified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateModified_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.DateModified;
                }
                private static void _DateModified_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateModified = global::LightSwitchApplication.tblNote.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _DateModified_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.DateModified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry
                    RelatedTo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry(
                        "RelatedTo",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedTo_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedTo_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedTo_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedTo_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedTo_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedTo_OnValueChanged);
                private static void _RelatedTo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._RelatedTo, sf);
                }
                private static bool _RelatedTo_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.RelatedTo_IsReadOnly(ref result);
                    return result;
                }
                private static void _RelatedTo_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RelatedTo_Validate(r);
                }
                private static global::System.Nullable<int> _RelatedTo_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.RelatedTo;
                }
                private static void _RelatedTo_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.RelatedTo = v;
                }
                private static void _RelatedTo_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.RelatedTo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry
                    RelatedFrom = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Entry(
                        "RelatedFrom",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedFrom_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedFrom_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedFrom_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedFrom_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedFrom_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._RelatedFrom_OnValueChanged);
                private static void _RelatedFrom_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._RelatedFrom, sf);
                }
                private static bool _RelatedFrom_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.RelatedFrom_IsReadOnly(ref result);
                    return result;
                }
                private static void _RelatedFrom_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RelatedFrom_Validate(r);
                }
                private static global::System.Nullable<int> _RelatedFrom_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.RelatedFrom;
                }
                private static void _RelatedFrom_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.RelatedFrom = v;
                }
                private static void _RelatedFrom_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.RelatedFrom_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.problem>.Entry
                    problem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.problem>.Entry(
                        "problem",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._problem_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._problem_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._problem_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._problem_GetCoreImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._problem_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._problem_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._problem_Refresh,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._problem_OnValueChanged);
                private static void _problem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.problem>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._problem, sf);
                }
                private static bool _problem_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.problem_IsReadOnly(ref result);
                    return result;
                }
                private static void _problem_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.problem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _problem_GetCoreImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.problem;
                }
                private static global::LightSwitchApplication.problem _problem_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.problem, global::LightSwitchApplication.problem.DetailsClass>(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.problem, ref d._problem);
                }
                private static void _problem_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::LightSwitchApplication.problem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.problem, ref d._problem, (i, ev) => i.problem = ev, v);
                }
                private static void _problem_Refresh(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.problem, ref d._problem);
                }
                private static void _problem_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.problem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.State>.Entry
                    State = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.State>.Entry(
                        "State",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._State_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._State_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._State_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._State_GetCoreImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._State_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._State_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._State_Refresh,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._State_OnValueChanged);
                private static void _State_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.State>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._State, sf);
                }
                private static bool _State_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.State_IsReadOnly(ref result);
                    return result;
                }
                private static void _State_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.State_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _State_GetCoreImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.State;
                }
                private static global::LightSwitchApplication.State _State_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.State, global::LightSwitchApplication.State.DetailsClass>(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.State, ref d._State);
                }
                private static void _State_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::LightSwitchApplication.State v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.State, ref d._State, (i, ev) => i.State = ev, v);
                }
                private static void _State_Refresh(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.State, ref d._State);
                }
                private static void _State_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.State_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.tblUser>.Entry
                    tblUser = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.tblUser>.Entry(
                        "tblUser",
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._tblUser_Stub,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._tblUser_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._tblUser_Validate,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._tblUser_GetCoreImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._tblUser_GetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._tblUser_SetImplementationValue,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._tblUser_Refresh,
                        global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties._tblUser_OnValueChanged);
                private static void _tblUser_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblNote.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.tblUser>.Data> c, global::LightSwitchApplication.tblNote.DetailsClass d, object sf)
                {
                    c(d, ref d._tblUser, sf);
                }
                private static bool _tblUser_ComputeIsReadOnly(global::LightSwitchApplication.tblNote e)
                {
                    bool result = false;
                    e.tblUser_IsReadOnly(ref result);
                    return result;
                }
                private static void _tblUser_Validate(global::LightSwitchApplication.tblNote e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.tblUser_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _tblUser_GetCoreImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.ImplementationEntity.tblUser;
                }
                private static global::LightSwitchApplication.tblUser _tblUser_GetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.tblUser, global::LightSwitchApplication.tblUser.DetailsClass>(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.tblUser, ref d._tblUser);
                }
                private static void _tblUser_SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass d, global::LightSwitchApplication.tblUser v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.tblUser, ref d._tblUser, (i, ev) => i.tblUser = ev, v);
                }
                private static void _tblUser_Refresh(global::LightSwitchApplication.tblNote.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.tblNote.DetailsClass.PropertySetProperties.tblUser, ref d._tblUser);
                }
                private static void _tblUser_OnValueChanged(global::LightSwitchApplication.tblNote e)
                {
                    e.tblUser_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, int>.Data _NoteID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string>.Data _note;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _addDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, string>.Data _uid;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data _IsPrivate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data _IsFuture;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _FutureDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data _NoteType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data _Time;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateModified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data _RelatedTo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::System.Nullable<int>>.Data _RelatedFrom;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.problem>.Data _problem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.State>.Data _State;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblNote, global::LightSwitchApplication.tblNote.DetailsClass, global::LightSwitchApplication.tblUser>.Data _tblUser;
            
        }
    
        #endregion
    }
    
    #endregion
}
