

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class SectorGroup : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the SectorGroup entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SectorGroup()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SectorGroup(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SectorGroup> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.SectorGroup.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SectorGroup_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SectorGroup_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SectorGroupID
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.SectorGroupID);
            }
            set
            {
                global::LightSwitchApplication.SectorGroup.DetailsClass.SetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.SectorGroupID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SectorGroupID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SectorGroupID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SectorGroupID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SectorGroupName
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.SectorGroupName);
            }
            set
            {
                global::LightSwitchApplication.SectorGroup.DetailsClass.SetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.SectorGroupName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SectorGroupName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SectorGroupName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SectorGroupName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.SectorGroup.DetailsClass.SetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Company> Companies
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Companies);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Company> CompaniesQuery
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetQuery(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Companies);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Contact> Contacts
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Contacts);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Contact> ContactsQuery
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetQuery(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Contacts);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Dealing> Dealings
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Dealings);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Dealing> DealingsQuery
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetQuery(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Dealings);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.problem> problems
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.problems);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.problem> problemsQuery
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetQuery(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.problems);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Sector Sector
        {
            get
            {
                return global::LightSwitchApplication.SectorGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Sector);
            }
            set
            {
                global::LightSwitchApplication.SectorGroup.DetailsClass.SetValue(this, global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Sector, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sector_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sector_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sector_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.SectorGroup,
                global::LightSwitchApplication.SectorGroup.DetailsClass,
                global::LightSwitchApplication.SectorGroup.DetailsClass.IImplementation,
                global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.SectorGroupID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass>.Entry
                __SectorGroupEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass>.Entry(
                    global::LightSwitchApplication.SectorGroup.DetailsClass.__SectorGroup_CreateNew,
                    global::LightSwitchApplication.SectorGroup.DetailsClass.__SectorGroup_Created,
                    global::LightSwitchApplication.SectorGroup.DetailsClass.__SectorGroup_AllowSaveWithErrors);
            private static global::LightSwitchApplication.SectorGroup __SectorGroup_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SectorGroup> es)
            {
                return new global::LightSwitchApplication.SectorGroup(es);
            }
            private static void __SectorGroup_Created(global::LightSwitchApplication.SectorGroup e)
            {
                e.SectorGroup_Created();
            }
            private static bool __SectorGroup_AllowSaveWithErrors(global::LightSwitchApplication.SectorGroup e)
            {
                bool result = false;
                e.SectorGroup_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, int> SectorGroupID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.SectorGroupID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string> SectorGroupName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.SectorGroupName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Company> Companies
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Companies) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Company>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Contact> Contacts
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Contacts) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Contact>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Dealing> Dealings
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Dealings) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Dealing>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.problem> problems
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.problems) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.problem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Sector> Sector
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Sector) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Sector>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int SectorGroupID { get; set; }
                new string SectorGroupName { get; set; }
                new string Description { get; set; }
                new global::System.Collections.IEnumerable Companies { get; }
                new global::System.Collections.IEnumerable Contacts { get; }
                new global::System.Collections.IEnumerable Dealings { get; }
                new global::System.Collections.IEnumerable problems { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Sector { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, int>.Entry
                    SectorGroupID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, int>.Entry(
                        "SectorGroupID",
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupID_Stub,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupID_ComputeIsReadOnly,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupID_Validate,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupID_GetImplementationValue,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupID_SetImplementationValue,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupID_OnValueChanged);
                private static void _SectorGroupID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SectorGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, int>.Data> c, global::LightSwitchApplication.SectorGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._SectorGroupID, sf);
                }
                private static bool _SectorGroupID_ComputeIsReadOnly(global::LightSwitchApplication.SectorGroup e)
                {
                    bool result = false;
                    e.SectorGroupID_IsReadOnly(ref result);
                    return result;
                }
                private static void _SectorGroupID_Validate(global::LightSwitchApplication.SectorGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SectorGroupID_Validate(r);
                }
                private static int _SectorGroupID_GetImplementationValue(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.SectorGroupID;
                }
                private static void _SectorGroupID_SetImplementationValue(global::LightSwitchApplication.SectorGroup.DetailsClass d, int v)
                {
                    d.ImplementationEntity.SectorGroupID = v;
                }
                private static void _SectorGroupID_OnValueChanged(global::LightSwitchApplication.SectorGroup e)
                {
                    e.SectorGroupID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string>.Entry
                    SectorGroupName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string>.Entry(
                        "SectorGroupName",
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupName_Stub,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupName_ComputeIsReadOnly,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupName_Validate,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupName_GetImplementationValue,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupName_SetImplementationValue,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._SectorGroupName_OnValueChanged);
                private static void _SectorGroupName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SectorGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string>.Data> c, global::LightSwitchApplication.SectorGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._SectorGroupName, sf);
                }
                private static bool _SectorGroupName_ComputeIsReadOnly(global::LightSwitchApplication.SectorGroup e)
                {
                    bool result = false;
                    e.SectorGroupName_IsReadOnly(ref result);
                    return result;
                }
                private static void _SectorGroupName_Validate(global::LightSwitchApplication.SectorGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SectorGroupName_Validate(r);
                }
                private static string _SectorGroupName_GetImplementationValue(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.SectorGroupName;
                }
                private static void _SectorGroupName_SetImplementationValue(global::LightSwitchApplication.SectorGroup.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SectorGroupName = v;
                }
                private static void _SectorGroupName_OnValueChanged(global::LightSwitchApplication.SectorGroup e)
                {
                    e.SectorGroupName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SectorGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string>.Data> c, global::LightSwitchApplication.SectorGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.SectorGroup e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.SectorGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.SectorGroup.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.SectorGroup e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Company>.Entry
                    Companies = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Company>.Entry(
                        "Companies",
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Companies_Stub,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Companies_GetReferencedEntities,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Companies_GetEntityCollection);
                private static void _Companies_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SectorGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Company>.Data> c, global::LightSwitchApplication.SectorGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._Companies, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Company> _Companies_GetReferencedEntities(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass>(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Companies, ref d._Companies);
                }
                private static global::System.Collections.IEnumerable _Companies_GetEntityCollection(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.Companies;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Contact>.Entry
                    Contacts = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Contact>.Entry(
                        "Contacts",
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Contacts_Stub,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Contacts_GetReferencedEntities,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Contacts_GetEntityCollection);
                private static void _Contacts_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SectorGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Contact>.Data> c, global::LightSwitchApplication.SectorGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._Contacts, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Contact> _Contacts_GetReferencedEntities(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Contact, global::LightSwitchApplication.Contact.DetailsClass>(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Contacts, ref d._Contacts);
                }
                private static global::System.Collections.IEnumerable _Contacts_GetEntityCollection(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.Contacts;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Dealing>.Entry
                    Dealings = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Dealing>.Entry(
                        "Dealings",
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Dealings_Stub,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Dealings_GetReferencedEntities,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Dealings_GetEntityCollection);
                private static void _Dealings_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SectorGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Dealing>.Data> c, global::LightSwitchApplication.SectorGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._Dealings, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Dealing> _Dealings_GetReferencedEntities(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Dealing, global::LightSwitchApplication.Dealing.DetailsClass>(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Dealings, ref d._Dealings);
                }
                private static global::System.Collections.IEnumerable _Dealings_GetEntityCollection(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.Dealings;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.problem>.Entry
                    problems = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.problem>.Entry(
                        "problems",
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._problems_Stub,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._problems_GetReferencedEntities,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._problems_GetEntityCollection);
                private static void _problems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SectorGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.problem>.Data> c, global::LightSwitchApplication.SectorGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._problems, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.problem> _problems_GetReferencedEntities(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.problem, global::LightSwitchApplication.problem.DetailsClass>(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.problems, ref d._problems);
                }
                private static global::System.Collections.IEnumerable _problems_GetEntityCollection(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.problems;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Sector>.Entry
                    Sector = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Sector>.Entry(
                        "Sector",
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Sector_Stub,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Sector_ComputeIsReadOnly,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Sector_Validate,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Sector_GetCoreImplementationValue,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Sector_GetImplementationValue,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Sector_SetImplementationValue,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Sector_Refresh,
                        global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties._Sector_OnValueChanged);
                private static void _Sector_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SectorGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Sector>.Data> c, global::LightSwitchApplication.SectorGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._Sector, sf);
                }
                private static bool _Sector_ComputeIsReadOnly(global::LightSwitchApplication.SectorGroup e)
                {
                    bool result = false;
                    e.Sector_IsReadOnly(ref result);
                    return result;
                }
                private static void _Sector_Validate(global::LightSwitchApplication.SectorGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Sector_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Sector_GetCoreImplementationValue(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.Sector;
                }
                private static global::LightSwitchApplication.Sector _Sector_GetImplementationValue(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Sector, global::LightSwitchApplication.Sector.DetailsClass>(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Sector, ref d._Sector);
                }
                private static void _Sector_SetImplementationValue(global::LightSwitchApplication.SectorGroup.DetailsClass d, global::LightSwitchApplication.Sector v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Sector, ref d._Sector, (i, ev) => i.Sector = ev, v);
                }
                private static void _Sector_Refresh(global::LightSwitchApplication.SectorGroup.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.SectorGroup.DetailsClass.PropertySetProperties.Sector, ref d._Sector);
                }
                private static void _Sector_OnValueChanged(global::LightSwitchApplication.SectorGroup e)
                {
                    e.Sector_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, int>.Data _SectorGroupID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string>.Data _SectorGroupName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Company>.Data _Companies;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Contact>.Data _Contacts;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Dealing>.Data _Dealings;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.problem>.Data _problems;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.SectorGroup, global::LightSwitchApplication.SectorGroup.DetailsClass, global::LightSwitchApplication.Sector>.Data _Sector;
            
        }
    
        #endregion
    }
    
    #endregion
}
