

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class department : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the department entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public department()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public department(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.department> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.department.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void department_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void department_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int department_id
        {
            get
            {
                return global::LightSwitchApplication.department.DetailsClass.GetValue(this, global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.department_id);
            }
            set
            {
                global::LightSwitchApplication.department.DetailsClass.SetValue(this, global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.department_id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void department_id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void department_id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void department_id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string dname
        {
            get
            {
                return global::LightSwitchApplication.department.DetailsClass.GetValue(this, global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.dname);
            }
            set
            {
                global::LightSwitchApplication.department.DetailsClass.SetValue(this, global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.dname, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void dname_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void dname_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void dname_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.problem> problems
        {
            get
            {
                return global::LightSwitchApplication.department.DetailsClass.GetValue(this, global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.problems);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.problem> problemsQuery
        {
            get
            {
                return global::LightSwitchApplication.department.DetailsClass.GetQuery(this, global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.problems);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.department,
                global::LightSwitchApplication.department.DetailsClass,
                global::LightSwitchApplication.department.DetailsClass.IImplementation,
                global::LightSwitchApplication.department.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.department_id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass>.Entry
                __departmentEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass>.Entry(
                    global::LightSwitchApplication.department.DetailsClass.__department_CreateNew,
                    global::LightSwitchApplication.department.DetailsClass.__department_Created,
                    global::LightSwitchApplication.department.DetailsClass.__department_AllowSaveWithErrors);
            private static global::LightSwitchApplication.department __department_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.department> es)
            {
                return new global::LightSwitchApplication.department(es);
            }
            private static void __department_Created(global::LightSwitchApplication.department e)
            {
                e.department_Created();
            }
            private static bool __department_AllowSaveWithErrors(global::LightSwitchApplication.department e)
            {
                bool result = false;
                e.department_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.department.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, int> department_id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.department_id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, string> dname
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.dname) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, global::LightSwitchApplication.problem> problems
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.problems) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, global::LightSwitchApplication.problem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int department_id { get; set; }
                new string dname { get; set; }
                new global::System.Collections.IEnumerable problems { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, int>.Entry
                    department_id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, int>.Entry(
                        "department_id",
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._department_id_Stub,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._department_id_ComputeIsReadOnly,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._department_id_Validate,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._department_id_GetImplementationValue,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._department_id_SetImplementationValue,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._department_id_OnValueChanged);
                private static void _department_id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, int>.Data> c, global::LightSwitchApplication.department.DetailsClass d, object sf)
                {
                    c(d, ref d._department_id, sf);
                }
                private static bool _department_id_ComputeIsReadOnly(global::LightSwitchApplication.department e)
                {
                    bool result = false;
                    e.department_id_IsReadOnly(ref result);
                    return result;
                }
                private static void _department_id_Validate(global::LightSwitchApplication.department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.department_id_Validate(r);
                }
                private static int _department_id_GetImplementationValue(global::LightSwitchApplication.department.DetailsClass d)
                {
                    return d.ImplementationEntity.department_id;
                }
                private static void _department_id_SetImplementationValue(global::LightSwitchApplication.department.DetailsClass d, int v)
                {
                    d.ImplementationEntity.department_id = v;
                }
                private static void _department_id_OnValueChanged(global::LightSwitchApplication.department e)
                {
                    e.department_id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, string>.Entry
                    dname = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, string>.Entry(
                        "dname",
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._dname_Stub,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._dname_ComputeIsReadOnly,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._dname_Validate,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._dname_GetImplementationValue,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._dname_SetImplementationValue,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._dname_OnValueChanged);
                private static void _dname_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, string>.Data> c, global::LightSwitchApplication.department.DetailsClass d, object sf)
                {
                    c(d, ref d._dname, sf);
                }
                private static bool _dname_ComputeIsReadOnly(global::LightSwitchApplication.department e)
                {
                    bool result = false;
                    e.dname_IsReadOnly(ref result);
                    return result;
                }
                private static void _dname_Validate(global::LightSwitchApplication.department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.dname_Validate(r);
                }
                private static string _dname_GetImplementationValue(global::LightSwitchApplication.department.DetailsClass d)
                {
                    return d.ImplementationEntity.dname;
                }
                private static void _dname_SetImplementationValue(global::LightSwitchApplication.department.DetailsClass d, string v)
                {
                    d.ImplementationEntity.dname = v;
                }
                private static void _dname_OnValueChanged(global::LightSwitchApplication.department e)
                {
                    e.dname_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, global::LightSwitchApplication.problem>.Entry
                    problems = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, global::LightSwitchApplication.problem>.Entry(
                        "problems",
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._problems_Stub,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._problems_GetReferencedEntities,
                        global::LightSwitchApplication.department.DetailsClass.PropertySetProperties._problems_GetEntityCollection);
                private static void _problems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, global::LightSwitchApplication.problem>.Data> c, global::LightSwitchApplication.department.DetailsClass d, object sf)
                {
                    c(d, ref d._problems, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.problem> _problems_GetReferencedEntities(global::LightSwitchApplication.department.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.problem, global::LightSwitchApplication.problem.DetailsClass>(global::LightSwitchApplication.department.DetailsClass.PropertySetProperties.problems, ref d._problems);
                }
                private static global::System.Collections.IEnumerable _problems_GetEntityCollection(global::LightSwitchApplication.department.DetailsClass d)
                {
                    return d.ImplementationEntity.problems;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, int>.Data _department_id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, string>.Data _dname;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.department, global::LightSwitchApplication.department.DetailsClass, global::LightSwitchApplication.problem>.Data _problems;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Item : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Item entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Item()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Item(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Item> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Item.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Item_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Item_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ItemID
        {
            get
            {
                return global::LightSwitchApplication.Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> ItemType
        {
            get
            {
                return global::LightSwitchApplication.Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemType);
            }
            set
            {
                global::LightSwitchApplication.Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ItemNumber
        {
            get
            {
                return global::LightSwitchApplication.Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemNumber);
            }
            set
            {
                global::LightSwitchApplication.Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemNumber, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemNumber_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemNumber_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemNumber_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ItemSerial
        {
            get
            {
                return global::LightSwitchApplication.Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemSerial);
            }
            set
            {
                global::LightSwitchApplication.Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemSerial, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemSerial_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemSerial_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemSerial_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ItemName
        {
            get
            {
                return global::LightSwitchApplication.Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemName);
            }
            set
            {
                global::LightSwitchApplication.Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ItemName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Comment
        {
            get
            {
                return global::LightSwitchApplication.Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.Comment);
            }
            set
            {
                global::LightSwitchApplication.Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.Comment, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comment_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comment_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Comment_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return global::LightSwitchApplication.Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.DateCreated);
            }
            set
            {
                global::LightSwitchApplication.Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.DateCreated, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCreated_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCreated_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCreated_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateModified
        {
            get
            {
                return global::LightSwitchApplication.Item.DetailsClass.GetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.DateModified);
            }
            set
            {
                global::LightSwitchApplication.Item.DetailsClass.SetValue(this, global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.DateModified, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateModified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateModified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateModified_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Item,
                global::LightSwitchApplication.Item.DetailsClass,
                global::LightSwitchApplication.Item.DetailsClass.IImplementation,
                global::LightSwitchApplication.Item.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass>.Entry
                __ItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass>.Entry(
                    global::LightSwitchApplication.Item.DetailsClass.__Item_CreateNew,
                    global::LightSwitchApplication.Item.DetailsClass.__Item_Created,
                    global::LightSwitchApplication.Item.DetailsClass.__Item_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Item __Item_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Item> es)
            {
                return new global::LightSwitchApplication.Item(es);
            }
            private static void __Item_Created(global::LightSwitchApplication.Item e)
            {
                e.Item_Created();
            }
            private static bool __Item_AllowSaveWithErrors(global::LightSwitchApplication.Item e)
            {
                bool result = false;
                e.Item_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Item.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, int> ItemID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<int>> ItemType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string> ItemNumber
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemNumber) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string> ItemSerial
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemSerial) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string> ItemName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.ItemName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string> Comment
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.Comment) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>> DateCreated
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.DateCreated) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>> DateModified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties.DateModified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ItemID { get; }
                new global::System.Nullable<int> ItemType { get; set; }
                new string ItemNumber { get; set; }
                new string ItemSerial { get; set; }
                new string ItemName { get; set; }
                new string Comment { get; set; }
                new string Description { get; set; }
                new global::System.Nullable<global::System.DateTime> DateCreated { get; set; }
                new global::System.Nullable<global::System.DateTime> DateModified { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, int>.Entry
                    ItemID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, int>.Entry(
                        "ItemID",
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemID_Stub,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemID_Validate,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemID_OnValueChanged);
                private static void _ItemID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, int>.Data> c, global::LightSwitchApplication.Item.DetailsClass d, object sf)
                {
                    c(d, ref d._ItemID, sf);
                }
                private static bool _ItemID_ComputeIsReadOnly(global::LightSwitchApplication.Item e)
                {
                    bool result = false;
                    e.ItemID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ItemID_Validate(global::LightSwitchApplication.Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ItemID_Validate(r);
                }
                private static int _ItemID_GetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d)
                {
                    return d.ImplementationEntity.ItemID;
                }
                private static void _ItemID_OnValueChanged(global::LightSwitchApplication.Item e)
                {
                    e.ItemID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<int>>.Entry
                    ItemType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<int>>.Entry(
                        "ItemType",
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemType_Stub,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemType_Validate,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemType_GetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemType_SetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemType_OnValueChanged);
                private static void _ItemType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Item.DetailsClass d, object sf)
                {
                    c(d, ref d._ItemType, sf);
                }
                private static bool _ItemType_ComputeIsReadOnly(global::LightSwitchApplication.Item e)
                {
                    bool result = false;
                    e.ItemType_IsReadOnly(ref result);
                    return result;
                }
                private static void _ItemType_Validate(global::LightSwitchApplication.Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ItemType_Validate(r);
                }
                private static global::System.Nullable<int> _ItemType_GetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d)
                {
                    return d.ImplementationEntity.ItemType;
                }
                private static void _ItemType_SetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.ItemType = v;
                }
                private static void _ItemType_OnValueChanged(global::LightSwitchApplication.Item e)
                {
                    e.ItemType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Entry
                    ItemNumber = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Entry(
                        "ItemNumber",
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemNumber_Stub,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemNumber_ComputeIsReadOnly,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemNumber_Validate,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemNumber_GetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemNumber_SetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemNumber_OnValueChanged);
                private static void _ItemNumber_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Data> c, global::LightSwitchApplication.Item.DetailsClass d, object sf)
                {
                    c(d, ref d._ItemNumber, sf);
                }
                private static bool _ItemNumber_ComputeIsReadOnly(global::LightSwitchApplication.Item e)
                {
                    bool result = false;
                    e.ItemNumber_IsReadOnly(ref result);
                    return result;
                }
                private static void _ItemNumber_Validate(global::LightSwitchApplication.Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ItemNumber_Validate(r);
                }
                private static string _ItemNumber_GetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d)
                {
                    return d.ImplementationEntity.ItemNumber;
                }
                private static void _ItemNumber_SetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ItemNumber = v;
                }
                private static void _ItemNumber_OnValueChanged(global::LightSwitchApplication.Item e)
                {
                    e.ItemNumber_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Entry
                    ItemSerial = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Entry(
                        "ItemSerial",
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemSerial_Stub,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemSerial_ComputeIsReadOnly,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemSerial_Validate,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemSerial_GetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemSerial_SetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemSerial_OnValueChanged);
                private static void _ItemSerial_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Data> c, global::LightSwitchApplication.Item.DetailsClass d, object sf)
                {
                    c(d, ref d._ItemSerial, sf);
                }
                private static bool _ItemSerial_ComputeIsReadOnly(global::LightSwitchApplication.Item e)
                {
                    bool result = false;
                    e.ItemSerial_IsReadOnly(ref result);
                    return result;
                }
                private static void _ItemSerial_Validate(global::LightSwitchApplication.Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ItemSerial_Validate(r);
                }
                private static string _ItemSerial_GetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d)
                {
                    return d.ImplementationEntity.ItemSerial;
                }
                private static void _ItemSerial_SetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ItemSerial = v;
                }
                private static void _ItemSerial_OnValueChanged(global::LightSwitchApplication.Item e)
                {
                    e.ItemSerial_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Entry
                    ItemName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Entry(
                        "ItemName",
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemName_Stub,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemName_Validate,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemName_GetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemName_SetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._ItemName_OnValueChanged);
                private static void _ItemName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Data> c, global::LightSwitchApplication.Item.DetailsClass d, object sf)
                {
                    c(d, ref d._ItemName, sf);
                }
                private static bool _ItemName_ComputeIsReadOnly(global::LightSwitchApplication.Item e)
                {
                    bool result = false;
                    e.ItemName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ItemName_Validate(global::LightSwitchApplication.Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ItemName_Validate(r);
                }
                private static string _ItemName_GetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d)
                {
                    return d.ImplementationEntity.ItemName;
                }
                private static void _ItemName_SetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ItemName = v;
                }
                private static void _ItemName_OnValueChanged(global::LightSwitchApplication.Item e)
                {
                    e.ItemName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Entry
                    Comment = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Entry(
                        "Comment",
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Comment_Stub,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Comment_ComputeIsReadOnly,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Comment_Validate,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Comment_GetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Comment_SetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Comment_OnValueChanged);
                private static void _Comment_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Data> c, global::LightSwitchApplication.Item.DetailsClass d, object sf)
                {
                    c(d, ref d._Comment, sf);
                }
                private static bool _Comment_ComputeIsReadOnly(global::LightSwitchApplication.Item e)
                {
                    bool result = false;
                    e.Comment_IsReadOnly(ref result);
                    return result;
                }
                private static void _Comment_Validate(global::LightSwitchApplication.Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Comment_Validate(r);
                }
                private static string _Comment_GetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d)
                {
                    return d.ImplementationEntity.Comment;
                }
                private static void _Comment_SetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Comment = v;
                }
                private static void _Comment_OnValueChanged(global::LightSwitchApplication.Item e)
                {
                    e.Comment_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Data> c, global::LightSwitchApplication.Item.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Item e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Item e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateCreated = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateCreated",
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateCreated_Stub,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateCreated_ComputeIsReadOnly,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateCreated_Validate,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateCreated_GetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateCreated_SetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateCreated_OnValueChanged);
                private static void _DateCreated_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Item.DetailsClass d, object sf)
                {
                    c(d, ref d._DateCreated, sf);
                }
                private static bool _DateCreated_ComputeIsReadOnly(global::LightSwitchApplication.Item e)
                {
                    bool result = false;
                    e.DateCreated_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateCreated_Validate(global::LightSwitchApplication.Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateCreated_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateCreated_GetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d)
                {
                    return d.ImplementationEntity.DateCreated;
                }
                private static void _DateCreated_SetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateCreated = global::LightSwitchApplication.Item.DetailsClass.TruncateDate(v);
                }
                private static void _DateCreated_OnValueChanged(global::LightSwitchApplication.Item e)
                {
                    e.DateCreated_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateModified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateModified",
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateModified_Stub,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateModified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateModified_Validate,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateModified_GetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateModified_SetImplementationValue,
                        global::LightSwitchApplication.Item.DetailsClass.PropertySetProperties._DateModified_OnValueChanged);
                private static void _DateModified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Item.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Item.DetailsClass d, object sf)
                {
                    c(d, ref d._DateModified, sf);
                }
                private static bool _DateModified_ComputeIsReadOnly(global::LightSwitchApplication.Item e)
                {
                    bool result = false;
                    e.DateModified_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateModified_Validate(global::LightSwitchApplication.Item e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateModified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateModified_GetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d)
                {
                    return d.ImplementationEntity.DateModified;
                }
                private static void _DateModified_SetImplementationValue(global::LightSwitchApplication.Item.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateModified = global::LightSwitchApplication.Item.DetailsClass.TruncateDate(v);
                }
                private static void _DateModified_OnValueChanged(global::LightSwitchApplication.Item e)
                {
                    e.DateModified_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, int>.Data _ItemID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<int>>.Data _ItemType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Data _ItemNumber;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Data _ItemSerial;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Data _ItemName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Data _Comment;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateCreated;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Item, global::LightSwitchApplication.Item.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateModified;
            
        }
    
        #endregion
    }
    
    #endregion
}
